# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: baleen37/appellofi

    working_directory: ~/repo

    steps:
      - checkout
      # run tests!
      - run: yarn test


