version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - ~/.cache/pip

      - restore_cache:
          keys:
           - docker-{{ checksum "Dockerfile" }}-{{ checksum "package.json" }}
           - docker-{{ checksum "Dockerfile" }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: docker-{{ checksum "Dockerfile" }}-{{ checksum "package.json" }}
          paths:
            - /caches/app.tar

      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
  deploy:
    working_directory: /app
      - run:
          name: Push application Docker image
          command:
            - .circleci/esc-deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        - requires:
          - build
