export default {
  FETCH_TRACKS: 'FETCH_TRACKS',
  RECEIVE_TRACKS: 'RECEIVE_TRACKS',
  PLAY_SONG: 'PLAY_SONG',
  PLAYER_PLAY: 'PLAYER_PLAY',
  PLAYER_PAUSE: 'PLAYER_PAUSE',
  PLAY_NEXT_SONG: 'PLAY_NEXT_SONG',
  PLAYER_PREV_SONG: 'PLAYER_PREV_SONG',
};
