export default {
  FETCH_TRACKS: 'FETCH_TRACKS',
  RECEIVE_TRACKS: 'RECEIVE_TRACKS',
  PLAY_SONG: 'PLAY_SONG',
  PLAYER_PLAY: 'PLAYER_PLAY',
  PLAYER_PAUSE: 'PLAYER_PAUSE',
  PLAYER_NEXT_SONGS: 'PLAYER_NEXT_SONGS',
  PLAYER_PREV_SONGS: 'PLAYER_PREV_SONGS',
};
